### PR TITLE
fix bug with resolving routes in v2.2

### LINKED ISSUE #30: Fatal Error Uncaught InvalidArgumentException: Class &quot;transaction&quot; does not exist. in /storage/ssd4/502/13888502/public_html/vendor/yabacon/paystack-php/src/Paystack/Helpers/Router.php:69
# Problem/Motivation
I'm getting this error on live server when trying to call the api for redirect user to payment page
0 /storage/ssd4/502/13888502/public_html/vendor/yabacon/paystack-php/src/Paystack.php(106): Yabacon\Paystack\Helpers\Router-&gt;__construct('transaction', Object(Yabacon\Paystack))
1 /storage/ssd4/502/13888502/public_html/framework/Models/Subscriptions.php(61): Yabacon\Paystack-&gt;__get('transaction')

### PR DESCRIPTION
**Pull request by nwogu**
Fixes #30 

## Changes made by this pull request
-  Bug fixes by changing the way routes are resolved

### CODE REVIEW

File: src/Paystack/Helpers/Router.php [hunk 1]
```diff
@@ -96,10 +96,10 @@ private function getAllRoutes($paystackObj)
 
     private function getRouteClass($paystackObj)
     {
-        try {
+        if (isset($paystackObj->custom_routes[$this->route])) {
```
Comment (ibrahimlawal-paystack) [inline src/Paystack/Helpers/Router.php:99]: please use tests to ascertain the issue and its fix

Comment (nwogu) [reply src/Paystack/Helpers/Router.php:99]: Done @ibrahimlawal-paystack
